name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2
      name: Checkout source code

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
